---

- name: change hostname to '{{ rpi64box_hostname }}'
  hostname:
    name: '{{ rpi64box_hostname }}'
  notify: restart NetworkManager

- name: change /etc/hosts
  template:
    src: 'etc/hosts.j2'
    dest: '/etc/hosts'
    mode: '0644'
  when: ansible_hostname == rpi64box_hostname
  notify: restart NetworkManager

- meta: flush_handlers
