---
- name: format release date using locales
  command: "date --date={{ rpi64box_release_date }} '+%-d %B %Y'"
  environment:
    - LC_ALL: '{{ item.1 }}'
  with_indexed_items: '{{ rpi64box_locales }}'
  register: 'formatted_dates'
  when: 'formatted_dates is not defined or item.0 < rpi64box_locales|length'

- name: set vars with formatted dates
  set_fact: '{{ item.0 | regex_replace("^(.*)_.*UTF-8$", "rpi64box_release_date_\1") }}={{ item.1.stdout }}'
  with_together:
    - '{{ rpi64box_locales }}'
    - '{{ formatted_dates.results }}'

- name: set summary string with formatted dates
  set_fact:
    rpi64box_moodle_summary: '{{ rpi64box_moodle_summary }}'
