---

- name: change username to '{{ rpi64box_username }}' in several files
  replace:
    path: '{{ item }}'
    regexp: '\b{{ rpi64box_rpi_username }}\b'
    replace: '{{ rpi64box_username }}'
  with_items: '{{ rpi64box_username_files }}'

- name: create sudoers file
  template:
    src: 'etc/sudoers.d/user.j2'
    dest: '/etc/sudoers.d/010_{{ rpi64box_username }}-nopasswd'
    mode: '0440'
    validate: 'visudo -cf %s'

- name: delete old sudoers file
  file:
    path: '/etc/sudoers.d/010_{{ rpi64box_rpi_username }}-nopasswd'
    state: 'absent'

- name: check presence of '/home/{{ rpi64box_rpi_username }}' directory
  stat:
    path: '/home/{{ rpi64box_rpi_username }}'
  register: pi_home_dir

- name: move user home directory
  command: 'mv -f /home/{{ rpi64box_rpi_username }} /home/{{ rpi64box_username }}'
  when: pi_home_dir.stat.exists and not pi_home_dir.stat.islnk

- name: check presence of '/home/{{ rpi64box_username }}' directory
  stat:
    path: '/home/{{ rpi64box_username }}'
  register: new_home_dir


- name: simlink to old directory
  file:
    src: '/home/{{ rpi64box_username }}'
    path: '/home/{{ rpi64box_rpi_username }}'
    state: 'link'
  when: new_home_dir.stat.exists

- name: change user password
  user:
    name: '{{ rpi64box_username }}'
    password: '{{ rpi64box_password | password_hash("md5") }}'

#- name: update .bashrc file (1)
#  lineinfile:
#    path: '/home/{{ rpi64box_rpi_username }}/.bashrc'
#    regexp: '^    PS1=.*01;32m.*01;34m.*$'
#    line: '    PS1="${debian_chroot:+($debian_chroot)}\[\e[0;93m\]\u\[\e[0m\]@\[\e[38;5;208m\]\h\[\e[0m\]:\[\e[0;96m\]\w \[\e[0m\]\$ "'
#    insertafter: '^if \[ "\$color_prompt" = yes \]; then'
#    backrefs: 'yes'
#  ignore_errors: yes

- name: update .bashrc file (2)
  blockinfile:
    path: '/home/{{ rpi64box_rpi_username }}/.bashrc'
    block: |
      alias l='ls -l'
      alias ll='ls -la'

      # Assign arrow keys to history search in bash
      bind '"\e[A":history-search-backward'
      bind '"\e[B":history-search-forward'
      # TAB cycles through the list of partial matches
      bind 'TAB:menu-complete'
  ignore_errors: yes
